<!DOCTYPE html>
<html>
<body>
<?php 
/** 
 * Descrição do arquivo: Primeiro programa php. 
 *
 * @package   [Nome do pacote de Classes, ou do sistema] 
 * @category  [Categoria a que o arquivo pertence] 
 * @name      [Apelido para o arquivo] 
 * @author    [nome do autor] <[e-mail do autor]> 
 * @copyright [Informações de Direitos de Cópia] 
 * @license   [link da licença] [Nome da licença] 
 * @link      [link de onde pode ser encontrado esse arquivo] 
 * @version   [Versão atual do arquivo] 
 * @since     [Arquivo existe desde: Data ou Versao: 15/11/2023] 
 */ 
 echo "Bem vindo PHP !";
?>
</body>
</html>
